// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuzRAq_0dXAcJS_jpJd-DShKAdNHTCwHw',
    appId: '1:903647399151:web:3425a51a7561b17b2f9f1a',
    messagingSenderId: '903647399151',
    projectId: 'campus-app-b5afd',
    authDomain: 'campus-app-b5afd.firebaseapp.com',
    storageBucket: 'campus-app-b5afd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZwS5QFxRKLaVXYppqI10abDBCoOoGCx4',
    appId: '1:903647399151:android:51913087f8aaecf72f9f1a',
    messagingSenderId: '903647399151',
    projectId: 'campus-app-b5afd',
    storageBucket: 'campus-app-b5afd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA54ZsVMITIKSZqzYP_kifl8AJCTyFZw5Y',
    appId: '1:903647399151:ios:65e5eab8446702ea2f9f1a',
    messagingSenderId: '903647399151',
    projectId: 'campus-app-b5afd',
    storageBucket: 'campus-app-b5afd.firebasestorage.app',
    iosBundleId: 'com.example.campusapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA54ZsVMITIKSZqzYP_kifl8AJCTyFZw5Y',
    appId: '1:903647399151:ios:65e5eab8446702ea2f9f1a',
    messagingSenderId: '903647399151',
    projectId: 'campus-app-b5afd',
    storageBucket: 'campus-app-b5afd.firebasestorage.app',
    iosBundleId: 'com.example.campusapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuzRAq_0dXAcJS_jpJd-DShKAdNHTCwHw',
    appId: '1:903647399151:web:4316befbe4ab16c32f9f1a',
    messagingSenderId: '903647399151',
    projectId: 'campus-app-b5afd',
    authDomain: 'campus-app-b5afd.firebaseapp.com',
    storageBucket: 'campus-app-b5afd.firebasestorage.app',
  );
}
